In [83]:
class MY_SLR:
    def __init__(self):
        self.m = None
        self.b = None

    
    def fit(self, X_train, y_train):
        num = 0
        den = 0
        for i in range(X_train.shape[0]):
            X_train = np.asarray(X_train).reshape(-1)
            y_train = np.asarray(y_train)
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self, X_test):
        predictions = []
        X_test = np.asarray(X_test).reshape(-1)
        for x in X_test:
            predictions.append(self.m * x + self.b)
        return np.array(predictions)

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('placement.csv')

In [4]:
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [5]:
X = df.iloc[:,0:1]

In [17]:
y = df.iloc[:,-1]

In [18]:
X.head()

   cgpa
0  6.89
1  5.12
2  7.82
3  7.42
4  6.94

In [19]:
y.head()

0    3.26
1    1.98
2    3.25
3    3.67
4    3.57
Name: package, dtype: float64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [23]:
X_train.head()

     cgpa
79   7.18
197  7.21
38   8.62
24   6.53
122  5.12

In [24]:
X_train.shape

(160, 1)

In [84]:
lr = MY_SLR()

In [86]:
lr.fit(X_train.values, y_train)

0.5742564727019197
-1.0270069374542108

In [35]:
type(X_train)

pandas.core.frame.DataFrame

In [87]:
print(lr.predict(X_test.values))

[2.78031348 3.13635249 3.1995207  2.38981908 3.52684689 3.76803461
 3.16506531 2.54486832 3.17655044 3.4923915  1.90744364 2.34962112
 3.6876387  2.75734322 3.47516381 3.04447145 2.32665086 3.20526327
 2.17734418 3.314372   2.45298729 2.90090734 3.32011456 2.87219451
 3.33734226 2.19457187 1.41932564 2.7114027  3.18229301 2.32665086
 3.74506435 2.95833298 3.68189614 2.97556068 2.59080884 3.34882738
 2.47595755 3.07318428 4.17575671 2.95833298]

In [68]:
X_test.shape

(40, 1)